[package]
name = "working_with_linked_lists" # Rust For Data Engineering.
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { workspace = true }
clap = { workspace = true, features = ["derive"] }
