[package]
name = "copilot_ecosystem_module" # Rust For Data Engineering.
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive"] }
rand = { workspace = true }
